Jose remarks
reconhub/argus pull request #16
Opened 2018-04-17 15:05 UTC by olgamie

Apply the remarks to the reports based on Jose e-mail.

The changes correspond to font size, chart layouts, regarranging table order or column order.

2018-04-19 10:48 UTC, marekrogala requested changes
nice! ptal at comments

2018-04-19 10:48 UTC, marekrogala commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +nrow_charts <- ceiling(max(length(plots_disease_occurance_w12)/2, 1))
bad style -- missing spaces around binary operator

2018-04-19 10:48 UTC, marekrogala commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +                             i18n$t("phone"),
:+1: btw, what would do you think about making an alias like `m <- i18n$t` (shorthand for `message`) so that this is very short, like `m("phone")` (`t` is already taken by a function in base)

normalli I'm against shorthand names, but in special cases where it is clearly documented and increases readability instead of descreasing it, it's worth considering

2018-04-19 10:48 UTC, marekrogala commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +  select(receptionDate, name_Site, name_parentSite, contactName, contactPhoneNumber, message)
where does the inconsistency in column names come from?

2018-04-19 10:48 UTC, marekrogala commented on src/plots/ploting.R
> +  xref='paper',
nit: style

2018-04-19 10:48 UTC, marekrogala commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +                     new = c(i18n$t("reception_Date"), i18n$t("name_Site"), i18n$t("name_parentSite"), i18n$t("contactName"),
`reception_Date` vs `receptionDate`
`reception_Date` looks weird -- like a mix of camel case and underscores?

2018-04-27 11:09 UTC, olgamie commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +nrow_charts <- ceiling(max(length(plots_disease_occurance_w12)/2, 1))
done

2018-04-27 11:10 UTC, olgamie commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +                             i18n$t("phone"),
that could be nice :) But I don't think we have time for that :)

2018-04-27 11:10 UTC, olgamie commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +  select(receptionDate, name_Site, name_parentSite, contactName, contactPhoneNumber, message)
This is new requirement from argus

2018-04-27 11:11 UTC, olgamie commented on src/dashboard_input_scripts/epidemiological_dashboard_input.R
> +                     new = c(i18n$t("reception_Date"), i18n$t("name_Site"), i18n$t("name_parentSite"), i18n$t("contactName"),
This is how column names are named in the data which I received.

2018-04-27 11:12 UTC, marekrogala approved these changes

2018-04-27 11:13 UTC, merged